### ISSUE TITLE
so i try to run the retrieve link it has this issue

### ISSUE THREAD

**Issue by DWAA1660** [edwardmfho/YouTubeReportBot#1]
`C:\Users\dwatn\OneDrive\Desktop\YouTubeReportBot-master\retrieve_link.py:40: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  self.driver = webdriver.Chrome(executable_path='/usr/local/bin/chromedriver')
Traceback (most recent call last):
  File "C:\Users\dwatn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 74, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dwatn\OneDrive\Desktop\YouTubeReportBot-master\retrieve_link.py", line 77, in <module>
    bot = ReportBot()
  File "C:\Users\dwatn\OneDrive\Desktop\YouTubeReportBot-master\retrieve_link.py", line 40, in __init__
    self.driver = webdriver.Chrome(executable_path='/usr/local/bin/chromedriver')
  File "C:\Users\dwatn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\dwatn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\dwatn\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 84, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home` not really sure what this means

**Comment by gtv2vxdp7r-crypto** [comment]
Can someone use it on this channel this person is a convicted ped I knew them and I was the one who got them put away before https://youtu.be/m7pK0F6KFv0
